import exceptions.*;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;


/**
 * <h3>Description:</h3>
 * A class for describing the basic information of users, which will use interface of JDBC.<br>
 * <br>
 * The member of team who is responsible for database should implement the interface.<br>
 * <br>
 * <br>
 * <h3>Requirements (for developers):</h3>
 * <ol start="1">
 *     <li>Need a table contain the information of all users.</li>
 *
 *         <ol>
 *         <li>The ID should be generated by database automatically. (increase by one from last user)</li>
 *         <br>
 *         <li>Find out whether the account name already exist or not.</li>
 *         <br>
 *         <li>A method that can insert a new row into the user_info table.</li>
 *         <br>
 *         <li>A method that can query any row's attribute by specific account name or ID.</li>
 *         <br>
 *         <li>A method that can update any attribute in specific row.</li>
 *         </ol>
 *
 *     <li>Need another table contain every user's address(es).</li>
 * </ol>
 * <br>
 * @author Qi, Hanzhong<br>
 * E-Mail: <a href=mailto:17722018@bjtu.edu.cn>17722018@bjtu.edu.cn</a><br>
 * ID: 17722018<br>
 * LU ID: 34648127<br>
 */
public class User {

    public Gender gender;
    public int age;
    public String name, password, phoneNumber;

    protected Date inDate;
    protected int ID;
    protected List<Address> addresses;
    protected String account;


    /**
     * Constructor to create a new user.<br>
     * <br>
     * <br>
     * @param age user age
     * @param phoneNumber phone number of the user
     * @param name user's real name
     * @param account user's account name (will be used while login, should be exclusive)
     * @param password password for verifying.
     * @param gender male, female or secret.<br>
     * <br>
     * <br>
     * @exception AgeException The age should greater than 18.
     * @exception PhoneNumberFormatException Should not contain non-numeric character.
     * @exception AccountNameExistException The name is already exist.
     * @exception PasswordFormatException Password should combined by 8-20 English capital and small characters and numbers.
     */
    public User(int age, String phoneNumber, String name, String account, String password, Gender gender)
            throws AgeException, PhoneNumberFormatException, AccountNameExistException, PasswordFormatException {

        if (age < 18)
            throw new AgeException();

        if (Pattern.compile("\\D+").matcher(phoneNumber).matches())
            throw new PhoneNumberFormatException();

        // TODO 判断账户名称是否已经存在
        if (false)
            throw new AccountNameExistException();

        if (!Pattern.compile("^(?!\\d+$)(?![A-Za-z]+$)(?![a-z0-9]+$)(?![A-Z0-9]+$)[a-zA-Z0-9]+$").matcher(password).matches())
            throw new PasswordFormatException();

        this.age = age;
        this.phoneNumber = phoneNumber;
        this.name = name;
        this.account = account;
        this.password = password;
        this.gender = gender;
        inDate = new Date(System.currentTimeMillis());
        addresses = new ArrayList<Address>();

        // TODO 在数据库中建立条目，初始化 ID

    }


    /**
     * @param account account name
     * @param password password<br>
     * <br>
     * <br>
     * @return return a User that just has been authorized<br>
     * <br>
     * <br>
     * @exception AccountNotRegisteredException Account has not been registered.
     * @exception PasswordIncorrectException Incorrect password.
     */
    public static User login(String account, String password)
            throws AccountNotRegisteredException, PasswordIncorrectException {

        // TODO 根据 ID 或者 account name 来确认其是否存在于数据库中，然后验证密码。如果成功返回 User，否则抛出异常。
        return null;

    }


    /**
     * @param ID ID
     * @param password password<br>
     * <br>
     * <br>
     * @return return a User that just has been authorized<br>
     * <br>
     * <br>
     * @exception AccountNotRegisteredException Account has not been registered.
     * @exception PasswordIncorrectException Incorrect password.
     */
    public static User login(int ID, String password)
            throws AccountNotRegisteredException, PasswordIncorrectException {

        // TODO 根据 ID 或者 account name 来确认数据库是否存在，然后验证密码。如果成功返回 User，否则抛出异常。
        return null;

    }


    /**
     * Create a new user in database.<br>
     * <br>
     * <br>
     * @param newUser a instance of user
     */
    public static void register(User newUser) {

        // TODO 调用数据库接口的 INSERT 功能在数据库中建立新的用户
        // TODO 查询新建立的用户 ID 并初始化
        newUser.ID = 0;

    }


    public Address address(int ID) {

        return addresses.get(ID);

    }


    public int ID() {

        return ID;

    }


    public String account() {

        return account;

    }


    public String inDate() {

        SimpleDateFormat formatter= new SimpleDateFormat("yyyy-MM-dd");
        return formatter.format(inDate);

    }


    public void addAddress(String country, String province, String city, String countyOrDistrict, String detail) {

        addresses.add(new Address(country, province, city, countyOrDistrict, detail));

    }


    public void deleteAddress(int ID) {

        addresses.remove(ID);

    }


    public void saveChanges() {

        // TODO

    }

}
